# MLX Tutorial


## vectors

In [3]:
# using list 

a = [10,20,30,40,50]
print(a)

[10, 20, 30, 40, 50]


In [4]:
import mlx.core as mx

a = mx.array([10,20,30,40,50])

print(a)

array([10, 20, 30, 40, 50], dtype=int32)


In [5]:
a.shape

(5,)

In [6]:
a.dtype

mlx.core.int32

In [7]:
a.size

5

In [8]:
b = mx.array([10,20,30,40,50], mx.int16)
print(b)

array([10, 20, 30, 40, 50], dtype=int16)


In [9]:
b = mx.array([10,20,30,40,50], mx.float32)
print(b)

array([10, 20, 30, 40, 50], dtype=float32)


In [10]:
b = mx.array([10.02,20,30,40,50])
print(b)

array([10.02, 20, 30, 40, 50], dtype=float32)


In [17]:
a = mx.array([[10], [20], [30], [40], [50]])
a

array([[10],
       [20],
       [30],
       [40],
       [50]], dtype=int32)

In [14]:
a.shape, a.size, a.dtype

((5, 1), 5, mlx.core.int32)

In [ ]:
# numpy implementation
import numpy as np

a = np.array([[10], [20], [30], [40], [50]])
a, a.shape, a.size, a.dtype

(array([[10],
        [20],
        [30],
        [40],
        [50]]),
 (5, 1),
 5,
 dtype('int64'))

In [20]:
# Accessing arrays 

a = mx.array([10,20,30,40,50])

for x in range(a.size):
    a[x] = a[x]+ 5
    print(a[x])

print(a)

array(15, dtype=int32)
array(25, dtype=int32)
array(35, dtype=int32)
array(45, dtype=int32)
array(55, dtype=int32)
array([15, 25, 35, 45, 55], dtype=int32)


In [26]:
a = mx.array([10,20,30,40,50])

b = mx.add(a, 5)
c = mx.subtract(a, 3)
d = mx.multiply(a, 7)
e = mx.divide(a, 3)

print(a)
print(b)
print(c)
print(d)
print(e)

array([10, 20, 30, 40, 50], dtype=int32)
array([15, 25, 35, 45, 55], dtype=int32)
array([7, 17, 27, 37, 47], dtype=int32)
array([70, 140, 210, 280, 350], dtype=int32)
array([3.33333, 6.66667, 10, 13.3333, 16.6667], dtype=float32)


In [27]:
a = mx.array([10.42,20.90,30.75,40.12,50.36])

b = mx.add(a, 5)
c = mx.subtract(a, 3)
d = mx.multiply(a, 7)
e = mx.divide(a, 3)

print(a)
print(b)
print(c)
print(d)
print(e)

array([10.42, 20.9, 30.75, 40.12, 50.36], dtype=float32)
array([15.42, 25.9, 35.75, 45.12, 55.36], dtype=float32)
array([7.42, 17.9, 27.75, 37.12, 47.36], dtype=float32)
array([72.94, 146.3, 215.25, 280.84, 352.52], dtype=float32)
array([3.47333, 6.96667, 10.25, 13.3733, 16.7867], dtype=float32)


In [29]:
a = mx.array([10,20,30,40,50])

b = mx.sum(a)
c = mx.min(a)
d = mx.max(a)
e = mx.mean(a)
f = mx.std(a)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

array([10, 20, 30, 40, 50], dtype=int32)
array(150, dtype=int32)
array(10, dtype=int32)
array(50, dtype=int32)
array(30, dtype=float32)
array(14.1421, dtype=float32)


In [31]:
a = mx.array([[10], [20], [30], [40], [50]])
b = mx.array([[60], [70], [80], [90], [100]])

c = mx.add(a,b)
d = mx.subtract(a,b)
e = mx.multiply(a,b)
f = mx.divide(a,b)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

array([[10],
       [20],
       [30],
       [40],
       [50]], dtype=int32)
array([[60],
       [70],
       [80],
       [90],
       [100]], dtype=int32)
array([[70],
       [90],
       [110],
       [130],
       [150]], dtype=int32)
array([[-50],
       [-50],
       [-50],
       [-50],
       [-50]], dtype=int32)
array([[600],
       [1400],
       [2400],
       [3600],
       [5000]], dtype=int32)
array([[0.166667],
       [0.285714],
       [0.375],
       [0.444444],
       [0.5]], dtype=float32)


In [32]:
a = mx.array([10,20,30,40,50])
b = mx.array([60, 70, 80, 90, 100])

c = mx.add(a,b)
d = mx.subtract(a,b)
e = mx.multiply(a,b)
f = mx.divide(a,b)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

array([10, 20, 30, 40, 50], dtype=int32)
array([60, 70, 80, 90, 100], dtype=int32)
array([70, 90, 110, 130, 150], dtype=int32)
array([-50, -50, -50, -50, -50], dtype=int32)
array([600, 1400, 2400, 3600, 5000], dtype=int32)
array([0.166667, 0.285714, 0.375, 0.444444, 0.5], dtype=float32)


In [33]:
# dot product
a = mx.array([1,2,3], mx.float32)
b = mx.array([4,5,6], mx.float32)

c = mx.matmul(a,b)

print(a)
print(b)
print(c)

array([1, 2, 3], dtype=float32)
array([4, 5, 6], dtype=float32)
array(32, dtype=float32)


In [35]:
# dot product
a = mx.array([[1,2], [3, 4]], mx.float32)
b = mx.array([[4,5],[6,7]], mx.float32)

c = mx.matmul(a,b)

print(a)
print(b)
print(c)

array([[1, 2],
       [3, 4]], dtype=float32)
array([[4, 5],
       [6, 7]], dtype=float32)
array([[16, 19],
       [36, 43]], dtype=float32)


In [37]:
# Shaping 

a = mx.arange(10, 60, 10)

print(a)

array([10, 20, 30, 40, 50], dtype=int32)


In [38]:
a = mx.zeros([5,1])

print(a)

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=float32)


In [39]:
a = mx.arange(10,60,10)
b = mx.zeros(a.shape)

print(a)
print(b)

array([10, 20, 30, 40, 50], dtype=int32)
array([0, 0, 0, 0, 0], dtype=float32)


In [40]:
c = mx.random.randint(0, 100, a.shape)
print(c)

array([98, 65, 29, 83, 51], dtype=int32)


In [48]:
a = mx.array([[[10,20,30], [40, 50, 60]]])
b = mx.flatten(a)
c = mx.squeeze(a)
d = mx.expand_dims(c, 1)

print(a)
print(b)
print(c)
print(d)

array([[[10, 20, 30],
        [40, 50, 60]]], dtype=int32)
array([10, 20, 30, 40, 50, 60], dtype=int32)
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)
array([[[10, 20, 30]],
       [[40, 50, 60]]], dtype=int32)


In [ ]:
a = mx.array([1,20,30])
b = mx.array([40,50,60])

c = mx.concatenate([a,b])

print(a)
print(b)
print(c)

array([1, 20, 30], dtype=int32)
array([40, 50, 60], dtype=int32)
array([1, 20, 30, 40, 50, 60], dtype=int32)


In [49]:
a = mx.array([10,20,30,40,50])

b = mx.reshape(a, (5,1))

print(a)
print(b)

array([10, 20, 30, 40, 50], dtype=int32)
array([[10],
       [20],
       [30],
       [40],
       [50]], dtype=int32)


In [50]:
a = mx.array([10,20,30])

b = mx.broadcast_to(a, (3,3))

print(a)
print(b)

array([10, 20, 30], dtype=int32)
array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]], dtype=int32)


In [51]:
a = mx.array([[10,20,30], [40, 50, 60]])

b = mx.transpose(a)

print(a)
print(b)

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)
array([[10, 40],
       [20, 50],
       [30, 60]], dtype=int32)


In [53]:
a = mx.array([[10,20,30], [40, 50, 60]])
b = mx.array([[10,20,30], [40, 50, 60]])

c = mx.add(a,b, stream=mx.cpu)
d = mx.add(a,b, stream=mx.gpu)

print(a)
print(b)
print(c)
print(d)

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)
array([[20, 40, 60],
       [80, 100, 120]], dtype=int32)
array([[20, 40, 60],
       [80, 100, 120]], dtype=int32)


In [ ]:
mx.savez("test.npz")
